### ISSUE TITLE
Oracle SSO form changed

### ISSUE THREAD

**Issue by antoineco** [typekpb/oradown#1]
I've been using this script successfully until I recently noticed something changed on the Oracle side.

The new endpoint for the Oracle SSO service is https://login.oracle.com/oaam_server/loginAuth.do

This endpoint expects the following form data: 
```
clientOffset:2
fk:8091956_aee7b4d7724a1632e1b18d3f8a0da8fb050141253cdf680960f2ab3bc2e66862
userid:myid
pass:mypass
```

The `fk` input comes from a hidden field:
```html
<input type="hidden" id="fk" name="fk" value="8091956_aee7b4d7724a1632e1b18d3f8a0da8fb050141253cdf680960f2ab3bc2e66862">
```

**Comment by typekpb** [comment]
interesting, the CI (on travis) seems to be working just fine (https://travis-ci.org/typekpb/oradown).
@antoineco anyway, any chance for creating PR for this?

**Comment by antoineco** [comment]
Yes because the test only asserts that a file is present, but actually all you get is a HTML document:

```console
$ file jdk-8u141-linux-x64.tar.gz 
jdk-8u141-linux-x64.tar.gz: HTML document text, ASCII text, with very long lines, with no line terminators
```

I'll try to understand the new flow better and submit a PR 👍

**Comment by typekpb** [comment]
Excelent, thanks!
